version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - JWT_SECRET=seu_jwt_secret_super_seguro_aqui
      - DATABASE_URL=file:/app/data/dev.db
    volumes:
      - ./data:/app/data
      - ./src:/app/src
      - ./prisma:/app/prisma
    command: sh -c "npx prisma migrate deploy && npm start"
    restart: unless-stopped

  # Opcional: PostgreSQL como alternativa
  # postgres:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: financial_db
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data: